### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by JarnoRFB** [shoeffner/cvloop#20] opened 2017-10-25 14:59 UTC
I installed `cvloop` with conda and tried to run it in jupyter. I get this error

```
TypeError                                 Traceback (most recent call last)
~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    236 
    237     if 'png' in formats:
--> 238         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    239     if 'retina' in formats or 'png2x' in formats:
    240         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    120 
    121     bytes_io = BytesIO()
--> 122     fig.canvas.print_figure(bytes_io, **kw)
    123     data = bytes_io.getvalue()
    124     if fmt == 'svg':

~/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2216                 bbox_filtered = []
   2217                 for a in bbox_artists:
-> 2218                     bbox = a.get_window_extent(renderer)
   2219                     if a.get_clip_on():
   2220                         clip_box = a.get_clip_box()

~/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/image.py in get_window_extent(self, renderer)
    759 
    760     def get_window_extent(self, renderer=None):
--> 761         x0, x1, y0, y1 = self._extent
    762         bbox = Bbox.from_extents([x0, y0, x1, y1])
    763         return bbox.transformed(self.axes.transData)

TypeError: 'NoneType' object is not iterable
```

Moreover in the console where jupyter is running I get 
```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
```

My conda environment looks like this

```
name: cv
channels:
- conda-forge
- defaults
dependencies:
- alembic=0.9.6=py_0
- asn1crypto=0.22.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- bleach=2.0.0=py36_0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- cairo=1.14.6=4
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- cryptography=2.0.3=py36_0
- cvloop=0.3.4=py36_0
- cycler=0.10.0=py36_0
- dask-core=0.15.4=py_0
- dbus=1.10.22=0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.1=0
- ffmpeg=3.2.4=1
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- harfbuzz=1.3.4=2
- hdf5=1.8.18=1
- html5lib=0.999999999=py36_0
- icu=58.1=1
- idna=2.6=py36_1
- imageio=2.2.0=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.3=py_0
- jasper=1.900.1=4
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jpeg=9b=1
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=1
- libsodium=1.0.10=0
- libtiff=4.0.7=0
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.5=0
- mako=1.0.7=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- nbgrader=0.5.3=py36_0
- ncurses=5.9=10
- networkx=2.0=py36_0
- notebook=5.2.0=py36_1
- numpy=1.13.3=py36_blas_openblas_200
- olefile=0.44=py36_0
- openblas=0.2.19=2
- opencv=3.3.0=py36_blas_openblas_200
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- pcre=8.39=0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.3.0=py36_0
- pip=9.0.1=py36_0
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=17.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pysocks=1.6.7=py36_0
- python=3.6.3=0
- python-dateutil=2.6.1=py36_0
- python-editor=1.0.3=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- pyzmq=16.0.2=py36_2
- qt=5.6.2=3
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- scikit-image=0.13.0=py36_2
- scikit-learn=0.19.1=py36_blas_openblas_200
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=36.6.0=py36_1
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- toolz=0.8.2=py_2
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.6=py36_0
- x264=20131217=3
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- pip:
  - backports.functools-lru-cache==1.4
  - dask==0.15.4
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
```

`cvloop` was working for around nine month ago on the same computer.

Please look into it if you have time as we would like to use `cvloop` for the new computer vision homeworks. Thanks

**Comment by shoeffner** [comment] 2017-10-25 19:29
I was not able to fully replicate your environment as `conda create -f environment.yml` had troubles with some dependencies... I added the channel `qttesting` and the channel `anaconda-fusion` to install `qt=5.6.2` and some other dependencies. After some back and forth between the dependencies I got it "close enough". The diff between your (`<`) and my (`>`) environment is now:
```
< - qt=5.6.2=3
> - qt=5.6.2=h9e3eb04_4

> - appnope=0.1.0=py36_0

< - libgfortran=3.0.0=1
> - libgfortran=3.0.0=0
```

So only for qt and fortran we have slightly different versions and I have `appnope=0.1.0`.

While I am also getting warnings:
`[IPKernelApp] WARNING | No such comm: 568cb9f0eead45e7bd826ca468d0d23c`
which seem to have to do with some protocol changes in jupyter notebooks (? or similar) I have no troubles viewing the stream when trying the examples notebook.

```
No such comm target registered: jupyter.widget.version
```
This might be a problem with your jupyter installation. Since also appnope is missing in your environment, maybe uninstalling jupyter and/or ipykernel (or just installing appnope) might fix it. But this error should not be related:
```
VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy
```
Either your webcam is/was in use by another program or maybe it is an OS related error, similar to maybe [https://github.com/opencv/opencv/issues/7974](https://github.com/opencv/opencv/issues/7974). Do you mind taking a look into that?

It might also help to downgrade OpenCV and test again – it looks like 9 months ago cvloop used OpenCV 3.2.0 while now 3.3.0 is installed in your and my environment.

Otherwise can you provide me with an example code you try to run? And what operating system are you using?

**Comment by JarnoRFB** [comment] 2017-10-25 19:43
I am and where when it was running on Ubuntu 16.04.

I just noticed that when running from the terminal everything works fine like e.g.
`python -c "from cvloop import cvloop; cvloop();"`

The error just occurs in the Jupyter notebook both with opencv 3.2 and 3.3.

**Comment by JarnoRFB** [comment] 2017-10-25 19:52
Now I found something else, in the notebook where I ran cvloopI had already imported `matplotlib`, when I run 
```
from cvloop import cvloop

cvloop() 
```

as the first notebook cell it works! Moreover I get this warning in the notebook where it does not work which I disregarded at first
```
/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/cvloop/cvloop.py:14: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-3d3efe512a66>", line 3, in <module>
    get_ipython().run_line_magic('matplotlib', 'inline')
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2978, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 308, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 229, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/__init__.py", line 1305, in use
    reload(sys.modules['matplotlib.backends'])
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('nbAgg')
```

**Comment by shoeffner** [comment] 2017-10-25 20:08
Yeah, that makes sense. cvloop tries to select the proper backend for you
if the inline (e.g. default) is set. Can you try it without a call to
`matplotlib.use(...)`?

**Comment by JarnoRFB** [comment] 2017-10-25 20:12
So now I guess I found the source of the problem
this works
```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
plt.rcParams['image.cmap'] = 'gray'

from cvloop import cvloop
```

cvloop()
this gives the described error
```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['image.cmap'] = 'gray'

from cvloop import cvloop

cvloop()
```

so setting the backend seems not to be the problem but using `%matplotlib inline`. Is there a a way to work around this?

**Comment by shoeffner** [comment] 2017-10-25 20:53
Yes, don't use `%matplotlib ` at all in a cell where you use cvloop - it
basically calls `matplotlib.use`. I could try to find out if I can make it
robust, but I doubt it - you simply can not use that command twice (in
notebooks per cell). So I highly suggest to either set it to notebook or
not setting it at all and letting cvloop do it for you.

**Comment by JarnoRFB** [comment] 2017-10-26 07:26
So the problem also occurs if `%matplotlib inline` and the call to `cvloop()` are in different cells. It would be convenient if one could generally have the none interactive input from `inline` in most cells and the interactive output only when `cvloop` is actually used.

**Comment by AndreaSuckro** [comment] 2017-10-26 08:40
It seems to be possible to set the interactive mode in a different way:

"
Starting with IPython 5.0 and matplotlib 2.0 you can avoid the use of IPython’s specific magic and use matplotlib.pyplot.ion()/matplotlib.pyplot.ioff() which have the advantages of working outside of IPython as well.
"
From [IPython Plotting Docs](http://ipython.readthedocs.io/en/stable/interactive/plotting.html). We could try that for the cvloop, but it would make the version requirements more strict. Will try it out later.

**Comment by krumnack** [comment] 2017-10-26 09:02
In the presence of `matplotlib.pyplot` I made the following observation: this first code does work
```
import matplotlib.pyplot as plt
plt.switch_backend('nbAgg')
from cvloop import cvloop
cvloop()
```
but the second results in the error:
```
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('nbAgg', warn=False, force=True)
from cvloop import cvloop
cvloop()
```

**Comment by shoeffner** [comment] 2017-10-26 12:59
This one works fine in my environment.
```python
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('nbAgg', warn=False, force=True)
from cvloop import cvloop
cvloop()
```

The only issue I can currently reproduce is
```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['image.cmap'] = 'gray'
from cvloop import cvloop
cvloop()
```
And I also get errors when I try to run other cells containing e.g. `%matplotlib notebook`.

I will look into it and try if I can get it to work in this case with what @AndreaSuckro suggests.

**Comment by JarnoRFB** [comment] 2017-10-26 13:02
With `matplotlib.pyplot.ion()` I get exactly the same error as with `%matplotlib inline`.
Using `%matplotlib notebook` several times is in fact no problem no for me.

**Comment by shoeffner** [comment] 2017-10-26 15:20
@krumnack's solution to use [matplotlib.pyplot.switch_backend('nbAgg')](http://matplotlib.org/api/_as_gen/matplotlib.pyplot.switch_backend.html#matplotlib.pyplot.switch_backend) seems to work well for all cases from these comments: https://github.com/shoeffner/cvloop/issues/20#issuecomment-339456362 and https://github.com/shoeffner/cvloop/issues/20#issuecomment-339600355.
It also works with python directly (`python -c "from cvloop import cvloop; cvloop()"`) and IPython.

I also made it slightly more robust by moving the switch into `cvloop.__init__()` instead of the `import`, as this way the imports do not matter.

What will **not** work is something like this:
```python
import numpy as np
import matplotlib.pyplot as plt
from cvloop import cvloop
x = np.linspace(-3.14, 3.14)
plt.plot(x, np.sin(x))
cvloop()
```
Because `cvloop()` needs to be the *plotting call* inside a cell.

You can try it out by using
`pip install -U -e git+https://github.com/shoeffner/cvloop.git@fix/issue20#egg=cvloop`
which should upgrade your currently installed version to the version on that branch.

On another side note, `plt.rcParams['image.cmap']` will not affect cvloop. Instead, if you just want to have a gray image, consider using the [color conversion example](https://render.githubusercontent.com/view/ipynb?commit=d8aa96af9600baee9b33d46376e219ad09745867&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73686f6566666e65722f63766c6f6f702f643861613936616639363030626165653962333364343633373665323139616430393734353836372f6578616d706c65732f63766c6f6f705f6578616d706c65732e6970796e62&nwo=shoeffner%2Fcvloop&path=examples%2Fcvloop_examples.ipynb&repository_id=74583611&repository_type=Repository#Color-conversion) `cvloop(convert_color=cv2.COLOR_BGR2GRAY)` or pass the cmap values: `cvloop(cmaps='gray')`.

It would be great if you could test it.

**Comment by JarnoRFB** [comment] 2017-10-26 20:06
Maybe it is my fault, but trying to pip install with the command provided by you gives me a permission denied error similar to https://stackoverflow.com/questions/21387456/cannot-install-a-specific-git-branch-on-github-with-pip-permission-denied-pub . Could you provide an `http` link to the commit?

**Comment by JarnoRFB** [comment] 2017-10-26 20:29
So using `%matplotlib inline` without any previous plotting call now does no longer cause an error!
However if I plot something in a previous cell like 
```
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
---------------------------------------------------------
img = np.random.randint(0, 255, size=900)
img.resize((30, 30))
plt.imshow(img)
---------------------------------------------------------
from cvloop import cvloop
cvloop()
```

now causes the error
```
TypeError                                 Traceback (most recent call last)
~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    236 
    237     if 'png' in formats:
--> 238         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    239     if 'retina' in formats or 'png2x' in formats:
    240         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/.anaconda3/envs/cv/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    120 
    121     bytes_io = BytesIO()
--> 122     fig.canvas.print_figure(bytes_io, **kw)
    123     data = bytes_io.getvalue()
    124     if fmt == 'svg':

~/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2216                 bbox_filtered = []
   2217                 for a in bbox_artists:
-> 2218                     bbox = a.get_window_extent(renderer)
   2219                     if a.get_clip_on():
   2220                         clip_box = a.get_clip_box()

~/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/image.py in get_window_extent(self, renderer)
    759 
    760     def get_window_extent(self, renderer=None):
--> 761         x0, x1, y0, y1 = self._extent
    762         bbox = Bbox.from_extents([x0, y0, x1, y1])
    763         return bbox.transformed(self.axes.transData)

TypeError: 'NoneType' object is not iterable
```
and in red
```
Traceback (most recent call last):
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/home/jarno/.anaconda3/envs/cv/lib/python3.6/site-packages/matplotlib/animation.py", line 1560, in _stop
    self.event_source.remove_callback(self._loop_delay)
AttributeError: 'NoneType' object has no attribute 'remove_callback'
```
and in the terminal
```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[IPKernelApp] WARNING | No such comm: f7e25b5addbb4a78a5e0e17e318317af
```
same with `plt.ion()`.

**Comment by shoeffner** [comment] 2017-10-28 16:20
This seems to be a problem with IPython and Matplotlib, as e.g. the following cells also don't work together (simple animation simplified from [here](http://matplotlib.org/examples/animation/simple_anim.html)):

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
```
```python
img = np.random.randint(0, 255, size=900)
img.resize((30, 30))
plt.imshow(img)
```
```python
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig, ax = plt.subplots()
x = np.arange(0, 2 * np.pi, 0.01)
line, = ax.plot(x, np.sin(x))

ani = animation.FuncAnimation(
    fig, lambda i: (line.set_ydata(np.sin(x + i / 10.0)), ), 
    np.arange(1, 200), interval=25, blit=False)
plt.show()
```

However, **doubling** the `%matplotlib notebook` seems to fix the problem!

Thus I changed cvloop to not use `switch_backend` but instead directly call IPython's magic commands – twice. Additionally I figured out that the following, which I claimed to be working before, indeed failed if run as the first cell:

```python
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('nbAgg', warn=False, force=True)
from cvloop import cvloop
cvloop()
```

I also fixed that by making sure that even if `nbAgg` is selected (e.g. via `force` as shown here), IPython's magics are used properly.

Can you please try again (`pip install -U -e git+https://github.com/shoeffner/cvloop.git@fix/issue20#egg=cvloop`)?

**Comment by krumnack** [comment] 2017-10-29 20:42
Hmm, this looks really strange ... after browsing the code for some time I think that our problem is due to at least two bugs!

**First**, in matplotlib: there is a strange cycle when destroying a figure:
*  `matplotlib._pylab_helpers.Gcf.destroy()/destroy_all()` will call `manager.destroy()` with `manager` being in our case `matplotlib.backends.backend_nbagg.FigureManagerNbAgg`
* `FigureManagerNbAgg`will then trigger a `'close_event'`
* the `'close_event'`will in turn fire `matplotlib._pylab_helpers.Gcf.destroy()`

I have no idea whether this cyclic structure makes sense, but it is the reason for our `AttributeError` in , `matplotlib/animation.py`: in the first round, the `'close_event'` also `_stops` the animation and hence it is gone in the second round.

The actual problem is in the function `Gcf.destroy_all()`: it first calls `manager.destroy()` and then removes the managers from the list (while  `Gcf.destroy()` does it the other way around). So here would be my proposal for a fix in `matplotlib/_pylab_helpers.py:`

```python
    @classmethod
    def destroy_all(cls):
        # this is need to ensure that gc is available in corner cases
        # where modules are being torn down after install with easy_install
        import gc  # noqa
        managers = list(cls.figs.values())
        cls.figs.clear()

        for manager in managers:
            manager.canvas.mpl_disconnect(manager._cidgcf)
            manager.destroy()

        cls._activeQue = []
        gc.collect(1)
```

**Second**, in IPython: why is `Gcf.destroy()` called at all? it turns out, that it is triggered by a `'post_execute'` event. The function `ipykernel.pylab.backend_inline.flush_figures` is registered as such an event by the `%matplotlib inline`. The problem is, that this happens twice when `%matplotlib inline` is called for the first time. You can check that by executing (with a fresh kernel):
```python
%matplotlib inline
import IPython
print(IPython.Application.instance().shell.events.callbacks['post_execute'])
```
which will show something like
```
[<function flush_figures at 0x7fb35f8fb158>, <function install_repl_displayhook.<locals>.post_execute at 0x7fb35f9061e0>, <function flush_figures at 0x7fb35f8fb158>]
```

I have traced back the problem to the following code in `IPython/core/interactiveshell.py`:
```python
def enable_matplotlib(self, gui=None):
    from IPython.core import pylabtools as pt
    gui, backend = pt.find_gui_and_backend(gui, self.pylab_gui_select)
    # ...
    pt.activate_matplotlib(backend) # <- in the first run, this will also call pt.configure_inline_support
    pt.configure_inline_support(self, backend) # configure_inline_support(inline) registers flush_figures
```
I have no good fix for this. You can repair it from the outside by 
```python
import IPython
from ipykernel.pylab.backend_inline import flush_figures
IPython.Application.instance().shell.events.unregister('post_execute', flush_figures)
```
or in the function `configure_inline_support` in `IPython/core/pylabtools.py`, where you could simply call `shell.events.unregister('post_execute', flush_figures)` twice. However, a real fix should prevent `flush_figures` to be registered twice (probably by preventing `configure_inline_support()` from being called twice).

Does any of this make sense?

**Comment by JarnoRFB** [comment] 2017-10-30 12:48
Honestly, I would need to look much deeper into matplotlib to be able to say whether this makes sense. However, the problem in the notebook with `%matplotlib inline` is fixed for me now! So I would consider this issue kind of fixed now, even though we might still look into more clean fixes. Could you push this fix to the `conda` package? We will ask the people to install the environment on next Wednesday.

**Comment by shoeffner** [comment] 2017-10-30 13:08
I forwarded @krumnack's analysis to ipython/ipython#10873 – for now I think the work around is "good enough". I will merge everything and push it to conda.

**Comment by shoeffner** [comment] 2017-10-30 13:27
Alright, you can find the new version ready on pypi (https://pypi.python.org/pypi/cvloop/0.3.5) and it should soon be available via conda (once the CI is done [here](https://github.com/conda-forge/cvloop-feedstock/pull/2) and it becomes merged).

**Closed as completed by shoeffner** 2017-10-30 13:27 UTC
Labels: bug

**Comment by RahmanBhuiyan** [comment] 2022-10-09 15:51
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/__init__.py", line 196, in process
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/animation.py", line 1467, in _stop
    self.event_source.remove_callback(self._loop_delay)
AttributeError: 'NoneType' object has no attribute `'remove_callback'```
```

How can I solve this error

**Comment by shoeffner** [comment] 2022-10-13 07:59
Please refer to https://github.com/ipython/ipython/issues/10873 –
essentially, not using `%matplotlib notebook` in the cell where you use the
cvloop should fix it.
Also, beware that I haven't maintained the project for about four years now
– and currently don't plan to – so things might have changed a lot.
